### ISSUE TITLE
Installation fails on Python 3.5

### ISSUE THREAD

**Issue by berezovskyi** [moliware/confumatrix#1]
```
$ pip install confumatrix
Collecting confumatrix
  Downloading confumatrix-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gf/6vj7ly457rjdj5mt9wwdh8jh0000gn/T/pip-build-8wpswpuc/confumatrix/setup.py", line 4, in <module>
        import confumatrix
      File "/private/var/folders/gf/6vj7ly457rjdj5mt9wwdh8jh0000gn/T/pip-build-8wpswpuc/confumatrix/confumatrix/__init__.py", line 1, in <module>
        from confumatrix import ConfuMatrix
    ImportError: cannot import name 'ConfuMatrix'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gf/6vj7ly457rjdj5mt9wwdh8jh0000gn/T/pip-build-8wpswpuc/confumatrix/
```

**Comment by berezovskyi** [comment]
SW versions:

Python 3.5.1
pip 8.1.2
virtualenv on Mac
